// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCK-AGpPTB76MC0t1Vjsycyp9vMxk8q18',
    appId: '1:292420228723:web:2230419bd36b7697ea3c06',
    messagingSenderId: '292420228723',
    projectId: 'finance-tracker-bb5d0',
    authDomain: 'finance-tracker-bb5d0.firebaseapp.com',
    storageBucket: 'finance-tracker-bb5d0.appspot.com',
    measurementId: 'G-E14WDECSDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0AFwKykVhYMQntrU6ac4ikEQFrBBxksw',
    appId: '1:292420228723:android:9235910ca1b07063ea3c06',
    messagingSenderId: '292420228723',
    projectId: 'finance-tracker-bb5d0',
    storageBucket: 'finance-tracker-bb5d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpacOwAcVRj8O1V3f32pubFNES_1LdXM',
    appId: '1:292420228723:ios:08d01f7e6c622142ea3c06',
    messagingSenderId: '292420228723',
    projectId: 'finance-tracker-bb5d0',
    storageBucket: 'finance-tracker-bb5d0.appspot.com',
    iosBundleId: 'com.example.financeTrackerApp',
  );
}
